security:
    authentication:
        type: PASSWORD
server:
    jetty:
        max-http-form-post-size: 10MB
    max-http-header-size: 10MB
    port: 12345
    servlet:
        context-path: /dolphinscheduler/
        session:
            timeout: 7200
    tomcat:
        max-http-form-post-size: 10MB
spring:
    messages:
        basename: i18n/messages
        encoding: UTF-8
    servlet:
        multipart:
            max-file-size: 1024MB
            max-request-size: 1024MB
