management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                exclude: env
                include: '*'
    server:
        port: 18082
security:
    authentication:
        type: PASSWORD
server:
    jetty:
        max-http-form-post-size: 10MB
        max-http-header-size: 10MB
    port: 12345
    servlet:
        context-path: /dolphinscheduler/
        session:
            timeout: 7200
    tomcat:
        max-http-form-post-size: 10MB
spring:
    devtools:
        restart:
            enable: true
    messages:
        basename: i18n/messages
        encoding: UTF-8
    mvc:
        cloud:
            sentinel:
                servlet:
                    block-page: /error
        resources:
            add-mappings: false
        throw-exception-if-no-handler-found: true
    profiles:
        active: dev
    servlet:
        multipart:
            max-file-size: 1024MB
            max-request-size: 1024MB
